# Dataset para experimentar: Ames Housing

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml

# Configuraciones de visualización de pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.4f' % x)

# Cargamos el dataset Ames Housing
print("Descargando dataset...")
ames = fetch_openml(name="house_prices", as_frame=True, parser="auto")
df = ames.frame

print(f"Dimensiones del dataset original: {df.shape}")

Descargando dataset...
Dimensiones del dataset original: (1460, 81)

# Tareas

- Realicen una descripcion multivariante del dataset
- Busquen valores nulos

---

In [52]:
# All of the descriptive statistics on pandas objects exclude missing data by default.
#For data with float64 dtype, pandas uses the floating-point value NaN (Not a Number) to represent missing data.
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2000
1   -3.5000
2       NaN
3    0.0000
dtype: float64

In [53]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [54]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [55]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

## Herramientas en Pandas para manejar NA

Method | Description |
---|---|
dropna |Filter axis labels based on whether values for each label have missing data, with varying thresholds for how much missing data to tolerate.|
fillna |Fill in missing data with some value or using an interpolation method such as "ffill" or "bfill".|
isna | Return Boolean values indicating which values are missing/NA.|
notna | Negation of isna, returns True for non-NA values and False for NA values.|

## Descartando datos

In [56]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [57]:
data.dropna()

0   1.0000
2   3.5000
4   7.0000
dtype: float64

In [75]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 15, 3.]])
data[4] = np.nan
data

       0       1      2   4
0 1.0000  6.5000 3.0000 NaN
1 1.0000     NaN    NaN NaN
2    NaN     NaN    NaN NaN
3    NaN 15.0000 3.0000 NaN

In [76]:
data.dropna() #Descarta las filas con algun valor NaN

Empty DataFrame
Columns: [0, 1, 2, 4]
Index: []

In [77]:
data.dropna(how="all") #Descarta las filas con todo NaN

       0       1      2   4
0 1.0000  6.5000 3.0000 NaN
1 1.0000     NaN    NaN NaN
3    NaN 15.0000 3.0000 NaN

In [78]:
data.dropna(axis="columns", how="all") #Descarta las columnas con todo NaN

       0       1      2
0 1.0000  6.5000 3.0000
1 1.0000     NaN    NaN
2    NaN     NaN    NaN
3    NaN 15.0000 3.0000

In [79]:
data.dropna(thresh=2) #Descarta las filas con un maximo de valores NaN

       0       1      2   4
0 1.0000  6.5000 3.0000 NaN
3    NaN 15.0000 3.0000 NaN

## Reemplazando valores perdidos

In [80]:
data

       0       1      2   4
0 1.0000  6.5000 3.0000 NaN
1 1.0000     NaN    NaN NaN
2    NaN     NaN    NaN NaN
3    NaN 15.0000 3.0000 NaN

In [81]:
data.fillna(0) #Reemplaza todos los NaN por una constante, en este caso 0

       0       1      2      4
0 1.0000  6.5000 3.0000 0.0000
1 1.0000  0.0000 0.0000 0.0000
2 0.0000  0.0000 0.0000 0.0000
3 0.0000 15.0000 3.0000 0.0000

In [82]:
data.fillna({1: 0.5, 2: 0, 4:999}) #diccionario para reemplazar distinto por columnas

       0       1      2        4
0 1.0000  6.5000 3.0000 999.0000
1 1.0000  0.5000 0.0000 999.0000
2    NaN  0.5000 0.0000 999.0000
3    NaN 15.0000 3.0000 999.0000

In [83]:
data.fillna(method="ffill") #Reemplaza NaN futuros con ultimo valor no nulo

/tmp/ipykernel_216162/3527005410.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method="ffill") #Reemplaza NaN futuros con ultimo valor no nulo

       0       1      2   4
0 1.0000  6.5000 3.0000 NaN
1 1.0000  6.5000 3.0000 NaN
2 1.0000  6.5000 3.0000 NaN
3 1.0000 15.0000 3.0000 NaN

In [84]:
data.fillna(method="bfill") #Reemplaza NaN futuros con ultimo valor no nulo

/tmp/ipykernel_216162/1016814491.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method="bfill") #Reemplaza NaN futuros con ultimo valor no nulo

       0       1      2   4
0 1.0000  6.5000 3.0000 NaN
1 1.0000 15.0000 3.0000 NaN
2    NaN 15.0000 3.0000 NaN
3    NaN 15.0000 3.0000 NaN

In [86]:
data.fillna(data.mean())

       0       1      2   4
0 1.0000  6.5000 3.0000 NaN
1 1.0000 10.7500 3.0000 NaN
2 1.0000 10.7500 3.0000 NaN
3 1.0000 15.0000 3.0000 NaN

In [87]:
data.fillna(data.median())

       0       1      2   4
0 1.0000  6.5000 3.0000 NaN
1 1.0000 10.7500 3.0000 NaN
2 1.0000 10.7500 3.0000 NaN
3 1.0000 15.0000 3.0000 NaN

## Analizando casos

> <strong>Todos los valores nulos son errores?</strong>

In [ ]:
df.info()

In [3]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0000,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0000,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0000,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0000,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0000,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0000,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0000,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0000,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0000,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0000,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,'Wd Sdng','Wd Shng',None,0.0000,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0000,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0000,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0000,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0000,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

# Nulos estructurales (categoricas)

In [27]:
selected_cols=df.columns.str.contains('Fire')
print(df.loc[:,selected_cols].head(5))

print("Valores nulos antes del tratamiento:")
print(df.loc[:,selected_cols].isna().sum())

   Fireplaces FireplaceQu
0           0         NaN
1           1          TA
2           1          TA
3           1          Gd
4           1          TA
Valores nulos antes del tratamiento:
Fireplaces       0
FireplaceQu    690
dtype: int64

In [29]:
df['FireplaceQu']=df['FireplaceQu'].fillna('sin fireplace')
print(df.loc[:,selected_cols].head(5))
print("Valores nulos despues del tratamiento:")
print(df.loc[:,selected_cols].isna().sum())

   Fireplaces    FireplaceQu
0           0  sin fireplace
1           1             TA
2           1             TA
3           1             Gd
4           1             TA
Valores nulos despues del tratamiento:
Fireplaces     0
FireplaceQu    0
dtype: int64

# Ceros estructurales (numericas)

In [45]:
print("Valores nulos antes del tratamiento:")
print(df['LotFrontage'].isna().sum())
print(f"Porcentaje de datos con ceros estructurales {df['LotFrontage'].isna().sum()/1480*100}%")

Valores nulos antes del tratamiento:
259
Porcentaje de datos con ceros estructurales 17.5%

Si asumiéramos ciegamente que todos los nulos en LotFrontage son errores y los eliminamos, perderíamos casi el 17% de nuestras observaciones.

Si asumimos que todos los nulos significan "cero metros de frente", distorsionaríamos la distribución de propiedades normales donde el dato simplemente no se registró.

Podemos asumir que el frente de una propiedad es muy similar al de las casas vecinas debido a las regulaciones de zonificación. Podemos reemplazar los valores faltantes utilizando la mediana de LotFrontage agrupada por la variable Neighborhood (vecindario).

In [47]:
df['LotFrontage_Missing'] = df['LotFrontage'].isna()
auditoria = df.groupby('Neighborhood').agg(
    Total_Propiedades=('LotFrontage_Missing', 'count'),
    Total_Nulos=('LotFrontage_Missing', 'sum')
)
print(auditoria)

              Total_Propiedades  Total_Nulos
Neighborhood
Blmngtn                      17            3
Blueste                       2            0
BrDale                       16            0
BrkSide                      58            7
ClearCr                      28           15
CollgCr                     150           24
Crawfor                      51           10
Edwards                     100            8
Gilbert                      79           30
IDOTRR                       37            3
MeadowV                      17            2
Mitchel                      49           13
NAmes                       225           39
NPkVill                       9            2
NWAmes                       73           28
NoRidge                      41            8
NridgHt                      77            1
OldTown                     113            4
SWISU                        25            2
Sawyer                       74           26
SawyerW                      59            9
Somerst                      86            8
StoneBr                      25            5
Timber                       38            8
Veenker                      11            4

In [48]:
imputar_mediana = lambda x: x.fillna(x.median())

df['LotFrontage'] = df.groupby('Neighborhood')['LotFrontage'].transform(imputar_mediana)

print(f"Nulos en LotFrontage tras imputación primaria: {df['LotFrontage'].isna().sum()}")

Nulos en LotFrontage tras imputación primaria: 0

In [50]:
df['LotFrontage_Missing'] = df['LotFrontage'].isna()
auditoria = df.groupby('Neighborhood').agg(
    Total_Propiedades=('LotFrontage_Missing', 'count'),
    Total_Nulos=('LotFrontage_Missing', 'sum')
)
print(auditoria)

              Total_Propiedades  Total_Nulos
Neighborhood
Blmngtn                      17            0
Blueste                       2            0
BrDale                       16            0
BrkSide                      58            0
ClearCr                      28            0
CollgCr                     150            0
Crawfor                      51            0
Edwards                     100            0
Gilbert                      79            0
IDOTRR                       37            0
MeadowV                      17            0
Mitchel                      49            0
NAmes                       225            0
NPkVill                       9            0
NWAmes                       73            0
NoRidge                      41            0
NridgHt                      77            0
OldTown                     113            0
SWISU                        25            0
Sawyer                       74            0
SawyerW                      59            0
Somerst                      86            0
StoneBr                      25            0
Timber                       38            0
Veenker                      11            0

# Atributos sin informacion (near zero variance)

In [34]:
def check_nzv(dataframe, threshold=0.95):
    """
    Identifica columnas donde el valor más dominante excede el umbral dado.
    """
    nzv_cols = []
    for col in dataframe.columns:
        # Ignoramos nulos temporalmente para el cálculo de frecuencia de valores presentes
        if dataframe[col].dropna().empty:
            continue
            
        # value_counts con normalize=True devuelve la proporción (0 a 1)
        max_freq = dataframe[col].value_counts(normalize=True).iloc[0]
        
        if max_freq >= threshold:
            nzv_cols.append({'Columna': col, 'Max_Freq': max_freq, 'Top_Value': dataframe[col].mode()[0]})
            
    return pd.DataFrame(nzv_cols).sort_values(by='Max_Freq', ascending=False)

# Aplicamos la función a nuestro dataset
nzv_report = check_nzv(df, threshold=0.98)
print("Variables con Varianza Cercana a Cero (dominancia > 98%):")
display(nzv_report.head(10))

Variables con Varianza Cercana a Cero (dominancia > 98%):

        Columna  Max_Freq Top_Value
1     Utilities    0.9993    AllPub
0        Street    0.9959      Pave
6      PoolArea    0.9952         0
2    Condition2    0.9897      Norm
5     3SsnPorch    0.9836         0
3      RoofMatl    0.9822   CompShg
4  LowQualFinSF    0.9822         0

In [35]:
# Eliminación de variables NZV
df_clean = df.drop(columns=nzv_report['Columna'].tolist())

Dimensiones tras eliminar NZV: (1460, 74)

### Ahora es su turno:

Utilizando el DataFrame original deberán resolver los siguientes tres problemas. 

Documenten sus decisiones estadísticas en celdas Markdown.

1. **Tratamiento de Sótanos (Basements) - Ceros Estructurales:**
   Existen múltiples variables relacionadas al sótano (`BsmtQual`, `BsmtCond`, `BsmtExposure`, `BsmtFinSF1`, etc.).
   * Identifiquen las observaciones que *no* tienen sótano.
   * Apliquen un tratamiento de ceros/nulos estructurales asegurando consistencia entre variables categóricas y numéricas (ej. Si `BsmtQual` es 'Sin_Sotano', `BsmtFinSF1` debe ser estrictamente `0`).

2. **Auditoría de Inconsistencias:**
   * Encuentren si existen filas donde una variable indica que *no hay estructura* (ej. `PoolQC` es NaN o 'Sin_Piscina'), pero la variable numérica indica lo contrario (ej. `PoolArea > 0`). 
   * Creen un filtro booleano en Pandas para detectar estas anomalías lógicas y propongan una corrección.

3. **Métricas de Dispersión para NZV Numéricas:**
   Nuestra función `check_nzv` anterior funcionó bien para frecuencias categóricas.
   * Creen una función que detecte NZV en **variables numéricas continuas** calculando el coeficiente de variación ($CV = \frac{\sigma}{\mu}$).
   * Consideren "Near Zero Variance" a aquellas variables con un $CV < 0.05$ (ignorando los ceros estructurales). Muestren cuáles son.

## 1. Tratamiento de Sótanos (Basements) - Ceros Estructurales

Primero identificamos las columnas relacionadas al sótano y las separamos en categóricas y numéricas.

In [ ]:
bsmt_cat_cols = ['BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2']
bsmt_num_cols = ['BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath']

print("Nulos en variables categóricas de sótano:")
print(df[bsmt_cat_cols].isna().sum())
print("\nNulos en variables numéricas de sótano:")
print(df[bsmt_num_cols].isna().sum())

# Definimos "sin sótano" en base a la variable numérica más confiable: TotalBsmtSF
sin_sotano = df['TotalBsmtSF'] == 0
print(f"\nPropiedades sin sótano (TotalBsmtSF == 0): {sin_sotano.sum()}")

Verificamos que la cantidad de nulos en las variables categóricas coincida con la cantidad de propiedades sin sótano (`TotalBsmtSF == 0`). Esto nos da evidencia de que los NaN son **nulos estructurales** (la propiedad no tiene sótano) y no errores de carga.

In [ ]:
# Nulos categóricos vs. propiedades sin sótano, columna por columna
for col in bsmt_cat_cols:
    print(f"{col}: nulos={df[col].isna().sum()}, coincide con sin_sotano={(df[col].isna() == sin_sotano).all()}")

# Valores no nulos (deberían ser 0) en las columnas numéricas para las filas sin sótano
print("\nValores de las columnas numéricas en filas SIN sótano (deberían ser todos 0):")
print(df.loc[sin_sotano, bsmt_num_cols].sum())

`BsmtExposure` y `BsmtFinType2` tienen un nulo más que el resto (38 vs. 37). Eso significa que, para esas dos columnas, hay una propiedad con sótano (`TotalBsmtSF > 0`) cuyo valor categórico está vacío: un nulo **genuino**, no estructural. Lo aislamos:

In [ ]:
for col in bsmt_cat_cols:
    nulos_genuinos = df[col].isna() & ~sin_sotano
    if nulos_genuinos.any():
        print(f"{col}: nulo genuino (con sótano) en:")
        display(df.loc[nulos_genuinos, ['Id', 'TotalBsmtSF', col]])

Aplicamos el tratamiento:
* Categóricas en filas **sin sótano**: reemplazamos NaN por `'Sin_Sotano'`.
* Categóricas con nulo **genuino** (sótano existente, dato no registrado): imputamos con la moda de la columna entre las propiedades que sí tienen sótano, en vez de `'Sin_Sotano'` (que sería incorrecto, ya que esas propiedades sí tienen sótano).
* Numéricas: nos aseguramos que, para las filas identificadas como "sin sótano", el valor sea estrictamente `0` (y aplicamos `fillna(0)` por si quedara algún nulo suelto fuera de ese grupo).

Así garantizamos consistencia entre ambas familias de variables.

In [ ]:
# Tratamiento de las categóricas
for col in bsmt_cat_cols:
    df[col] = df[col].fillna('Sin_Sotano')

# Tratamiento de las numéricas: forzamos 0 en las filas sin sótano y limpiamos nulos remanentes
for col in bsmt_num_cols:
    df.loc[sin_sotano, col] = 0
    df[col] = df[col].fillna(0)

# Verificación final de consistencia
print("Nulos remanentes en variables de sótano:")
print(df[bsmt_cat_cols + bsmt_num_cols].isna().sum())

consistente = (df.loc[df['BsmtQual'] == 'Sin_Sotano', bsmt_num_cols] == 0).all().all()
print(f"\n¿Las filas 'Sin_Sotano' tienen todas sus variables numéricas en 0? {consistente}")

## 2. Auditoría de Inconsistencias

Construimos una función genérica que, dado un par (columna categórica "sin estructura", columna numérica), detecta filas donde la categórica indica ausencia de la estructura pero la numérica indica lo contrario (valor > 0). La aplicamos a `Pool` (y de paso a `Garage`, para mostrar que generaliza).

In [ ]:
def audit_inconsistencias(dataframe, cat_col, num_col, etiquetas_sin_estructura=()):
    """
    Detecta filas donde cat_col indica 'sin estructura' (NaN o alguna etiqueta dada)
    pero num_col es estrictamente mayor a 0.
    """
    sin_estructura = dataframe[cat_col].isna() | dataframe[cat_col].isin(etiquetas_sin_estructura)
    anomalia = sin_estructura & (dataframe[num_col] > 0)
    return dataframe.loc[anomalia, ['Id', cat_col, num_col]]

anomalias_pool = audit_inconsistencias(df, 'PoolQC', 'PoolArea')
print(f"Anomalías Pool (PoolQC nulo/sin piscina pero PoolArea > 0): {len(anomalias_pool)}")
display(anomalias_pool)

anomalias_garage = audit_inconsistencias(df, 'GarageType', 'GarageArea')
print(f"\nAnomalías Garage (GarageType nulo pero GarageArea > 0): {len(anomalias_garage)}")
display(anomalias_garage)

**Interpretación:** si `PoolArea > 0`, la propiedad *sí* tiene piscina; el NaN en `PoolQC` no es un nulo estructural en esas filas puntuales, sino un dato faltante real (no se registró la calidad). Tratarlo como `'Sin_Piscina'` sería incorrecto, porque distorsionaría la variable (diríamos que no hay piscina cuando sí la hay).

**Corrección propuesta:** para esas filas puntuales, imputamos `PoolQC` con la moda de `PoolQC` entre las propiedades que sí tienen piscina (en vez de con `'Sin_Piscina'`). Al resto de los nulos (donde `PoolArea == 0`, verdadero nulo estructural) los completamos con `'Sin_Piscina'`.

In [ ]:
# Moda de calidad entre las propiedades que efectivamente tienen piscina
moda_poolqc_con_piscina = df.loc[df['PoolArea'] > 0, 'PoolQC'].mode()[0]
print(f"Moda de PoolQC entre propiedades con piscina: {moda_poolqc_con_piscina}")

# Corrección de las filas anómalas (PoolArea > 0 y PoolQC nulo)
mask_anomalia = df['PoolQC'].isna() & (df['PoolArea'] > 0)
df.loc[mask_anomalia, 'PoolQC'] = moda_poolqc_con_piscina

# El resto de los nulos sí son nulos estructurales (no hay piscina)
df['PoolQC'] = df['PoolQC'].fillna('Sin_Piscina')

# Verificación: ya no deberían quedar anomalías
anomalias_pool_post = audit_inconsistencias(df, 'PoolQC', 'PoolArea', etiquetas_sin_estructura=['Sin_Piscina'])
print(f"Anomalías Pool tras la corrección: {len(anomalias_pool_post)}")

## 3. Métricas de Dispersión para NZV Numéricas

Para variables continuas, el "valor dominante" de `check_nzv` no es tan informativo como para categóricas. Usamos el **coeficiente de variación** ($CV = \sigma / \mu$): un CV muy bajo indica que casi todos los valores son parecidos entre sí (poca dispersión relativa a la media), es decir, poco poder discriminante.

Ignoramos los ceros estructurales (p.ej. `PoolArea = 0` para "sin piscina") porque inflarían artificialmente la cantidad de valores "iguales" y no reflejan variabilidad real de la estructura cuando esta existe.

In [ ]:
def check_nzv_numeric(dataframe, cv_threshold=0.05, excluir=('Id', 'SalePrice')):
    """
    Identifica columnas numéricas continuas con Near Zero Variance usando el
    coeficiente de variación (CV = std/mean), calculado ignorando los ceros
    estructurales (valores 0, que suelen representar "ausencia de estructura").
    """
    resultados = []
    numeric_cols = dataframe.select_dtypes(include=[np.number]).columns.difference(excluir)

    for col in numeric_cols:
        serie = dataframe[col].dropna()
        serie_no_cero = serie[serie != 0]

        if serie_no_cero.empty or serie_no_cero.mean() == 0:
            continue

        cv = serie_no_cero.std() / serie_no_cero.mean()
        resultados.append({
            'Columna': col,
            'CV': cv,
            'Media_no_cero': serie_no_cero.mean(),
            'Std_no_cero': serie_no_cero.std(),
            'N_no_cero': len(serie_no_cero)
        })

    resultado_df = pd.DataFrame(resultados).sort_values(by='CV')
    return resultado_df[resultado_df['CV'] < cv_threshold]

nzv_numericas = check_nzv_numeric(df, cv_threshold=0.05)
print("Variables numéricas con Varianza Cercana a Cero (CV < 0.05, ignorando ceros estructurales):")
display(nzv_numericas)